MyBlog/Controllers/AuthorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.Service;
using System.Collections.Generic;
using System.Linq;
using X.PagedList;

namespace MyBlog.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IPostService _post;
        private readonly ICategoryService _category;
        private readonly ITagService _tag;
        private readonly IPostTagService _postTag;
        private readonly IMapper _mapper;
        private UserManager<BlogUser> _userManager;

        public AuthorController(IPostService post, ICategoryService category, ITagService tag, IPostTagService postTag, IMapper mapper, UserManager<BlogUser> userManager)
        {
            _post = post;
            _category = category;
            _tag = tag;
            _postTag = postTag;
            _mapper = mapper;
            _userManager = userManager;
        }

        public IActionResult Index(string id, PostSearchViewModel model)
        {
            if (model.PageIndex == 0) model.PageIndex = 1;
            if (model.PageSize == 0) model.PageSize = 10;

            IPagedList<Post>  posts = _post.GetPostList(o=>o.UserId == id).OrderByDescending(o => o.DateCreated).ToList().ToPagedList(model.PageIndex, model.PageSize); ;

            IEnumerable<PostListViewModel> postList = _mapper.Map<IEnumerable<PostListViewModel>>(posts);
            // create an instance of StaticPagedList with the mapped IEnumerable and original IPagedList metadata
            IPagedList<PostListViewModel> postListViewModel = new StaticPagedList<PostListViewModel>(postList, posts.GetMetaData());

            foreach (var item in postListViewModel)
            {
                item.PostTagList = _mapper.Map<List<PostTag>, List<PostTagViewModel>>(_postTag.GetPostTagList(o => o.PostId == item.PostId));
                foreach (var postTag in item.PostTagList)
                {
                    postTag.TagName = _tag.GetTag(o => o.TagId == postTag.TagId).TagName;
                }
                item.CategoryName = _category.GetCategory(o => o.CategoryId == item.CategoryId).CategoryName;
            }

            var authorModel = new PostAuthorViewModel { PostList = postListViewModel };
            authorModel.UserName = _userManager.FindByIdAsync(id).Result.UserName;

            authorModel.CountUserPosts = _post.GetCountUserPosts(id);
            authorModel.CountUserViews = _post.GetCountUserViews(id).Value;

            return View(authorModel);
        }
    }
}

MyBlog/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.Service;
using System.Collections.Generic;
using System.Linq;
using X.PagedList;

namespace MyBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostService _post;
        private readonly IPostTagService _postTag;
        private readonly ITagService _tag;
        private readonly ICategoryService _category;
        private readonly IMapper _mapper;
        private UserManager<BlogUser> _userManager;

        public HomeController(IPostService post, IPostTagService postTag, ITagService tag, ICategoryService category,IMapper mapper, UserManager<BlogUser> userManager)
        {
            _post = post;
            _mapper = mapper;
            _postTag = postTag;
            _tag = tag;
            _category = category;
            _userManager = userManager;
        }

        public IActionResult Index(PostSearchViewModel model)
        {
            if (model.PageIndex == 0) model.PageIndex = 1;
            if (model.PageSize == 0) model.PageSize = 10;

            ViewBag.SearchKey = model.SearchKey;

            var data = _post.GetPostList();
            if(!string.IsNullOrEmpty(model.SearchKey))
            {
               data =  data.FindAll(o => o.Content.Contains(model.SearchKey) || o.Title.Contains(model.SearchKey));
            }

            IPagedList<Post> posts = data.OrderByDescending(o=>o.DateCreated).ToList().ToPagedList(model.PageIndex,model.PageSize);
            // map to IEnumerable
            IEnumerable<PostListViewModel> postList = _mapper.Map<IEnumerable<PostListViewModel>>(posts);
            // create an instance of StaticPagedList with the mapped IEnumerable and original IPagedList metadata
            IPagedList<PostListViewModel> postListViewModel = new StaticPagedList<PostListViewModel>(postList, posts.GetMetaData());

            foreach (var item in postListViewModel)
            {
                item.UserName = _userManager.FindByIdAsync(item.UserId).Result.UserName;
                item.CategoryName = _category.GetCategory(o => o.CategoryId == item.CategoryId).CategoryName;
                item.PostTagList = _mapper.Map<List<PostTag>, List<PostTagViewModel>>(_postTag.GetPostTagList(o=>o.PostId == item.PostId));
                foreach (var postTag in item.PostTagList)
                {
                    postTag.TagName = _tag.GetTag(o => o.TagId == postTag.TagId).TagName;
                }
            }

            var postInfoModel = new PostInfoViewModel
            { 
                PostList = postListViewModel, 
                TagList = _mapper.Map<List<Tag>, List<TagViewModel>>(_tag.GetTagList()) ,
                CategoryList = _mapper.Map<List<Category>, List<CategoryViewModel>>(_category.GetCategoryList())
            };

            return View(postInfoModel);
        }

        public IActionResult Privacy() 
        {
            var posts = _post.GetPostList();

            return View(posts);
        }


        public IActionResult Post(int id)
        {
            var post = _post.GetPost(id);

            return View(post);
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            var result = _post.DeletePost(_post.GetPost(id));
            if (result)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

MyBlog/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.Repository;
using MyBlog.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _post;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICategoryService _category;
        private readonly ITagService _tag;
        private readonly IPostTagService _postTag;
        private readonly IMapper _mapper;
        private UserManager<BlogUser> _userManager;

        public PostController(IPostService post, IUnitOfWork unitOfWork, ICategoryService category, ITagService tag, IPostTagService postTag, IMapper mapper, UserManager<BlogUser> userManager)
        {
            _post = post;
            _unitOfWork = unitOfWork;
            _category = category;
            _tag = tag;
            _postTag = postTag;
            _mapper = mapper;
            _userManager = userManager;
        }

        public IActionResult Index(int id)
        {
            var post = _post.GetPost(id);
            _post.UpdatePostViews(post);

            var model = _mapper.Map<Post, PostListViewModel>(post);

            model.PostTagList = _mapper.Map<List<PostTag>, List<PostTagViewModel>>(_postTag.GetPostTagList(o => o.PostId == id));
            model.CategoryName = _category.GetCategory(o => o.CategoryId == model.CategoryId).CategoryName;
            model.UserName = _userManager.FindByIdAsync(model.UserId).Result.UserName;
            model.CountUserPosts = _post.GetCountUserPosts(model.UserId);
            model.CountUserViews = _post.GetCountUserViews(model.UserId).Value;
            foreach (var postTag in model.PostTagList)
            {
                postTag.TagName = _tag.GetTag(o => o.TagId == postTag.TagId).TagName;
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.CategoryList = _category.GetCategoryList();

            if (id.HasValue)
            {
                var post = _post.GetPost(id.Value);
                var model = _mapper.Map<Post, PostEditViewModel>(post);

                var tagList = _postTag.GetPostTagList(o => o.PostId == id.Value);
                var tagNameList = new List<string>();
                if (tagList.Count > 0)
                {
                    foreach (var item in tagList)
                    {
                        tagNameList.Add(_tag.GetTag(item.TagId).TagName);
                    }
                    model.TagString = string.Join(",", tagNameList);
                }

                return View(model);
            }
            return View(new PostEditViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(PostEditViewModel model)
        {
            BlogUser user = await _userManager.GetUserAsync(HttpContext.User);

            var post = _mapper.Map<PostEditViewModel, Post>(model);
            post.UserId = user.Id;

            var tagList = new List<string>();
            // 添加标签至数据库
            if (!string.IsNullOrEmpty(model.TagString))
            {
                tagList = model.TagString.Split(',').ToList();
                foreach (var item in tagList)
                {
                    if (_tag.GetTag(o => o.TagName == item) == null)
                    {
                        _tag.AddTag(new Tag { TagName = item, DateCreated = DateTime.Now }, false);
                    }
                }
                await _unitOfWork.SaveChangesAsync();
            }

            // 添加文章至数据库库
            if (model.PostId.HasValue)
            {
                var postId = _post.UpdatePost(post);

                _postTag.DeletePostTagList(o => o.PostId == post.PostId);

                foreach (var item in tagList)
                {
                    _postTag.AddPostTag(new PostTag { PostId = post.PostId, TagId = _tag.GetTag(o => o.TagName == item).TagId }, false);
                }

            }
            else
            {
                var postId = _post.AddPost(post);

                foreach (var item in tagList)
                {
                    _postTag.AddPostTag(new PostTag { PostId = postId, TagId = _tag.GetTag(o => o.TagName == item).TagId }, false);
                }
            }

            var result = await _unitOfWork.SaveChangesAsync();

            if (result)
            {
                return Json(new BaseResponse { Success = true, Message = "操作成功" });
            }
            else
            {
                return Json(new BaseResponse { Success = true, Message = "操作失败" });
            }
        }
    }
}

MyBlog/Views/Home/Index.cshtml
@model PostInfoViewModel

@{
    ViewData["Title"] = "首页";
}

<div class="display_flex justify-content-between">
    <div class="post-container mt-40">
        @Html.Partial("_PageList", Model.PostList)
    </div>
    <div class="right-container">
        <div class="card mt-40 post-card">
            <div class="card-body ">
                <h4 class="card-title post-title">分区</h4>
                <div>
                    @foreach (var item in Model.CategoryList)
                    {
                        <span class="tag-text">@item.CategoryName</span>
                    }
                </div>
            </div>
        </div>
        <div class="card mt-40 post-card">
            <div class="card-body ">
                <h4 class="card-title post-title">标签</h4>
                <div>
                    @foreach (var item in Model.TagList)
                    {
                        <span class="tag-text">@item.TagName</span>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MyBlog/Views/Home/_PageList.cshtml
@model IPagedList<PostListViewModel>

<form class="d-flex" style="width:710px" asp-action="Index" asp-controller="Home">
    <input class="form-control me-2" type="text" placeholder="查询文章" id="SearchKey" name="SearchKey" value="@ViewBag.SearchKey">
    <input hidden id="PageIndex" name="PageIndex" />
    <button type="submit" class="btn btn-search">
        <img class="img-search" src="~/img/search.svg" />
    </button>
</form>
@foreach (var item in Model)
{
    <div class="card mt-40 post-card">
        <div class="card-body ">
            <h4 class="card-title post-title text-left">@item.Title</h4>
            <div class="card-subtitle mb-2 post-info">
                作者<a asp-controller="Author" asp-action="Index" asp-route-id="@item.UserId" class="post-link"> @item.UserName </a>
                | 发表于 @item.DateCreated  | 分区 @item.CategoryName | 类型 @item.PostTypeId.ToString() | 阅读量 @item.Views
            </div>
            <div class="card-text post-content"><p class="post-content-text">@item.ContentString</p></div>
            <div class="display_flex justify-content-between">
                <div>
                    @foreach (var postTagItem in item.PostTagList)
                    {
                        <span class="tag-text">@postTagItem.TagName</span>
                    }
                </div>
                <div>
                    <a asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" class="post-link">阅读全文</a>
                </div>
            </div>
            <input type="hidden" id="post_id" value="@item.PostId" />
        </div>
    </div>
}
@Html.PagedListPager(Model, PageIndex => Url.Action("Index", new { PageIndex = PageIndex, SearchKey = @ViewBag.SearchKey }))