MyBlog/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.Service;
using System;
using System.Collections.Generic;

namespace MyBlog.Controllers
{
    public class AdminController : Controller
    {
        private readonly ICategoryService _category;
        private readonly IPostService _post;
        private readonly IPostTagService _postTag;
        private readonly IMapper _mapper;

        public AdminController(ICategoryService category, IPostTagService postTag, IMapper mapper, IPostService post)
        {
            _category = category;
            _mapper = mapper;
            _post = post;
            _postTag = postTag;
        }

        public IActionResult Index()
        {
            var list = _category.GetCategoryList();
            var model = _mapper.Map<List<Category>, List<CategoryViewModel>>(list);

            return View(model);
        }

        public IActionResult CategoryList()
        {
            var list = _category.GetCategoryList();
            var model = _mapper.Map<List<Category>, List<CategoryViewModel>>(list);

            return PartialView("_CategoryList", model);
        }
        [HttpPost]
        public IActionResult DeleteCategory(int id)
        {
            if (_post.GetPostList(o => o.CategoryId == id).Count > 0)
            {
                return Json(new BaseResponse { Success = false, Message = "有博文在此分类下，无法删除" });
            }

            var result = _category.DeleteCategory(_category.GetCategory(id));
            if (result)
            {
                return Json(new BaseResponse { Success = true, Message = "删除成功" });
            }
            return Json(new BaseResponse { Success = false, Message = "删除失败" });
        }
        public IActionResult GetCategoryEditLayer(int? id)
        {
            if (id.HasValue)
            {
                var item = _category.GetCategory(id.Value);
                var model = _mapper.Map<Category, CategoryViewModel>(item);

                return PartialView("_CategoryEdit", model);
            }
            else
            {
                return PartialView("_CategoryEdit", new CategoryViewModel());
            }
        }
        [HttpPost]
        public ActionResult EditCategory(CategoryEditViewModel model)
        {
            var item = _mapper.Map<CategoryEditViewModel, Category>(model);

            var result = new DataResponse<int>();
            if (model.CategoryId.Value == 0)
            {
                result = _category.AddCategory(item);
            }
            else
            {
                result = _category.UpdateCategory(item);
            }

            //if (result.Success)
            //{
            //    var data = _mapper.Map<Category, CategoryViewModel>(_category.GetCategory(result.data));

            //    return PartialView("_CategoryListItem", data);
            //}
            //else
            //{
            //    return Json(result);
            //}
            return Json(result);
        }

        public IActionResult PostList()
        {
            var list = _post.GetPostList();
            var model = _mapper.Map<List<Post>, List<PostListViewModel>>(list);

            return PartialView("_PostList", model);
        }
        public IActionResult DeletePost(int id)
        {
            var result = _post.DeletePost(_post.GetPost(id));
            if (result)
            {
                _postTag.DeletePostTagList(o => o.PostId == id);
                return Json(new BaseResponse { Success = true, Message = "删除成功" });
            }
            return Json(new BaseResponse { Success = false, Message = "删除失败" });
        }
    }
}

MyBlog/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.Repository;
using MyBlog.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _post;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICategoryService _category;
        private readonly ITagService _tag;
        private readonly IPostTagService _postTag;
        private readonly IMapper _mapper;
        private UserManager<BlogUser> _userManager;

        public PostController(IPostService post, IUnitOfWork unitOfWork, ICategoryService category, ITagService tag, IPostTagService postTag, IMapper mapper, UserManager<BlogUser> userManager)
        {
            _post = post;
            _unitOfWork = unitOfWork;
            _category = category;
            _tag = tag;
            _postTag = postTag;
            _mapper = mapper;
            _userManager = userManager;
        }

        public IActionResult Index(int id)
        {
            var post = _post.GetPost(id);
            _post.UpdatePostViews(post);

            var model = _mapper.Map<Post, PostListViewModel>(post);

            model.PostTagList = _mapper.Map<List<PostTag>, List<PostTagViewModel>>(_postTag.GetPostTagList(o => o.PostId == id));
            model.CategoryName = _category.GetCategory(o => o.CategoryId == model.CategoryId).CategoryName;
            model.UserName = _userManager.FindByIdAsync(model.UserId).Result.UserName;
            model.CountUserPosts = _post.GetCountUserPosts(model.UserId);
            model.CountUserViews = _post.GetCountUserViews(model.UserId).Value;
            foreach (var postTag in model.PostTagList)
            {
                postTag.TagName = _tag.GetTag(o => o.TagId == postTag.TagId).TagName;
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.CategoryList = _category.GetCategoryList();

            if (id.HasValue)
            {
                var post = _post.GetPost(id.Value);
                var model = _mapper.Map<Post, PostEditViewModel>(post);

                var tagList = _postTag.GetPostTagList(o => o.PostId == id.Value);
                var tagNameList = new List<string>();
                if (tagList.Count > 0)
                {
                    foreach (var item in tagList)
                    {
                        tagNameList.Add(_tag.GetTag(item.TagId).TagName);
                    }
                    model.TagString = string.Join(",", tagNameList);
                }

                return View(model);
            }
            return View(new PostEditViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(PostEditViewModel model)
        {
            BlogUser user = await _userManager.GetUserAsync(HttpContext.User);

            var post = _mapper.Map<PostEditViewModel, Post>(model);
            post.UserId = user.Id;

            var tagList = new List<string>();
            // 添加标签至数据库
            if (!string.IsNullOrEmpty(model.TagString))
            {
                tagList = model.TagString.Split(',').ToList();
                foreach (var item in tagList)
                {
                    if (_tag.GetTag(o => o.TagName == item) == null)
                    {
                        _tag.AddTag(new Tag { TagName = item, DateCreated = DateTime.Now }, false);
                    }
                }
                await _unitOfWork.SaveChangesAsync();
            }

            // 添加文章至数据库库
            if (model.PostId.HasValue)
            {
                var postId = _post.UpdatePost(post);

                _postTag.DeletePostTagList(o => o.PostId == post.PostId);

                foreach (var item in tagList)
                {
                    _postTag.AddPostTag(new PostTag { PostId = post.PostId, TagId = _tag.GetTag(o => o.TagName == item).TagId }, false);
                }

            }
            else
            {
                var postId = _post.AddPost(post);

                foreach (var item in tagList)
                {
                    _postTag.AddPostTag(new PostTag { PostId = postId, TagId = _tag.GetTag(o => o.TagName == item).TagId }, false);
                }
            }

            var result = await _unitOfWork.SaveChangesAsync();

            if (result)
            {
                return Json(new BaseResponse { Success = true, Message = "操作成功" });
            }
            else
            {
                return Json(new BaseResponse { Success = true, Message = "操作失败" });
            }
        }
    }
}

MyBlog/Views/Admin/Index.cshtml
@model List<CategoryViewModel>

@{
    ViewData["Title"] = "个人中心";
}

<div class="admin-container">
    <div class="w-25">
        <div class="admin-nav-container text-center card post-card">
            @Html.Partial("_Nav")
        </div>
    </div>
    <div id="admin_manage" class="ml-30 w-100">
        @Html.Partial("_CategoryList", Model)
    </div>
</div>

<style>
    #admin_manage button,#admin_manage a  { border: 1px solid #f2e7e7; }
</style>

MyBlog/Views/Admin/_CategoryEdit.cshtml
@model CategoryViewModel

@{ }

<form asp-action="EditCategory" asp-controller="Admin" method="post" id="edit_form" style=" margin: 30px;">
    <div class="form-group">
        <label class="letterSpacing_3">
            <span style="color:red">* </span>分类名称
        </label>
        <div>
            <input type="text" asp-for="CategoryName" class="form-control" autocomplete="off" />
        </div>
    </div>
    <div class="form-group mt-20">
        <div class="text-center">
            <button type="button" class="btn-edit" onclick="editCategory()">提交</button>
        </div>
    </div>
    <input type="hidden" asp-for="CategoryId" />
</form>

MyBlog/Views/Admin/_CategoryList.cshtml
@model List<CategoryViewModel>

<div class="display_flex justify-content-between mb-20">
    <h4 class="text-left nav-text nav-box">分类管理</h4>
    <button id="btn_add" type="button" class="btn btn-primary" onclick="getCategoryEditLayer()">新增分类</button>
</div>

<div class="text-center">
    <div class="table-responsive">
        <table class="table table-bordered table-hover" id="category_list">
            <thead class="thead-light">
                <tr>
                    <th class="wd_100">分类Id</th>
                    <th class="wd_100">分类名</th>
                    <th class="wd_100">分类创建时间</th>
                    <th class="wd_100">操作</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    @Html.Partial("_CategoryListItem", item)
                }
            </tbody>
        </table>
    </div>
</div>

MyBlog/Views/Admin/_CategoryListItem.cshtml
@model CategoryViewModel
<tr id="category_@Model.CategoryId">
    <td>@Model.CategoryId</td>
    <td>@Model.CategoryName</td>
    <td>@Model.DateCreated</td>
    <td>
        <button type="button" class="btn btn-primary btn-xs" size="" onclick="getCategoryEditLayer('@Model.CategoryId')">编辑</button>
        <button type="button" class="btn btn-danger btn-xs" size="" onclick="deleteCategory('@Model.CategoryId')">删除</button>
    </td>
</tr>

MyBlog/Views/Admin/_Nav.cshtml
<nav class="nav flex-column">
    <div>
        <h4 class="text-left nav-text nav-box">导航</h4>
        <div class="nav-btn-group">
            <button class="nav-link nav-box nav-link-color text-center" aria-current="page" onclick="getCategoryList()">分类管理</button>
            <button class="nav-link nav-box nav-link-color text-center" onclick="getPostList()">文章管理</button>
        </div>
    </div>
</nav>

MyBlog/Views/Admin/_PostList.cshtml
@model List<PostListViewModel>

<div class="display_flex justify-content-between mb-20"> 
    <h4 class="text-left nav-text nav-box">文章管理</h4>
    @*<button id="btn_add" type="button" class="btn btn-primary" onclick="">新增分类</button>*@
</div>

<div class="text-center">
    <div class="table-responsive">
        <table class="table table-bordered table-hover" id="post_list">
            <thead class="thead-light">
                <tr>
                    <th class="wd_100">文章Id</th>
                    <th class="wd_100">文章标题</th>
                    <th class="wd_100">浏览量</th>
                    <th class="wd_100">发表时间</th>
                    <th class="wd_100">操作</th>
                </tr>
            </thead>
            <tbody>
                @Html.Partial("_PostListItem", Model)
            </tbody>
        </table>
    </div>
</div>

MyBlog/Views/Admin/_PostListItem.cshtml
@model List<PostListViewModel>

@foreach (var item in Model)
{
<tr id="post_@item.PostId">
    <td>@item.PostId</td>
    <td>@item.Title</td>
    <td>@item.Views</td>
    <td>@item.DateCreated</td>
    <td>
        <a type="button" class="btn btn-primary btn-xs"  asp-action="Edit" asp-controller="Post" asp-route-id="@item.PostId">编辑</a>
        <button type="button" class="btn btn-danger btn-xs"  onclick="deletePost('@item.PostId')">删除</button>
    </td>
</tr>}